print("---------------------------------------------------|")
print("Modelo:____________________________________________|")
print("Marca :____________________________________________|")
print("Ano   :____________________________________________|")
print("Distância percorrida:______________________________|")
print("Litros de combustivel consumidos:__________________|")
print("Preço por litro:___________________________________|")
print("Total a pagar:_____________________________________|")
print("Km por litro:______________________________________|")

modelo = input("Informe o modelo: ")
marca = input("Informe a marca: ")
ano = int(input("Informe o ano do carro : "))
distancia = float(input("Informe a Distancia percorrida: "))
litro_consu = float(input("Informe o consumo do carro: "))
preco_litro = float(input("Informe preço por litro: "))
total_pagar = float(input("Informe total a pagar: "))
km_litro = float(input("Informe total Km por Litro"))

print("---------------------------------------------------|")
print("Modelo: ", modelo)
print("Marca : ", marca)
print("Ano   : ", ano)
print("Distância percorrida: " , distancia)
print("Litros de combustivel consumidos: ", litro_consu)
print("Preço por litro: ", preco_litro)
print("Total a pagar: ", total_pagar)
print("Km por litro: ", km_litro)